"""describe schema change

Revision ID: 3ddea9919e96
Revises: 4d92f4499488
Create Date: 2026-05-01 22:04:42.078095
"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = '3ddea9919e96'
down_revision = '4d92f4499488'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('deleteColumn2', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'deleteColumn2')
    # ### end Alembic commands ###
