"""add project deleteColumn

Revision ID: 4d92f4499488
Revises: 20260501_0002
Create Date: 2026-05-01 21:56:20.177061
"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = '4d92f4499488'
down_revision = '20260501_0002'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('deleteColumn', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'deleteColumn')
    # ### end Alembic commands ###
