"""describe schema change

Revision ID: ad577196c628
Revises: e232c589f6b6
Create Date: 2026-05-01 22:18:27.855359
"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = 'ad577196c628'
down_revision = 'e232c589f6b6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('deleteColumns', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'deleteColumns')
    # ### end Alembic commands ###
