"""describe schema change

Revision ID: adbb12eb9aeb
Revises: f7cdc57a6dd2
Create Date: 2026-05-01 22:11:55.501214
"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = 'adbb12eb9aeb'
down_revision = 'f7cdc57a6dd2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('deleteColumns', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'deleteColumns')
    # ### end Alembic commands ###
