"""describe schema change

Revision ID: d2021c002826
Revises: ad577196c628
Create Date: 2026-05-01 22:20:22.284663
"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = 'd2021c002826'
down_revision = 'ad577196c628'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'deleteColumns')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('deleteColumns', sa.TEXT(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
