"""describe schema change

Revision ID: e232c589f6b6
Revises: adbb12eb9aeb
Create Date: 2026-05-01 22:12:37.632183
"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = 'e232c589f6b6'
down_revision = 'adbb12eb9aeb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'deleteColumns')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('deleteColumns', sa.TEXT(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
