"""remove deleteColumn fields

Revision ID: f7cdc57a6dd2
Revises: 3ddea9919e96
Create Date: 2026-05-01 22:06:15.291371
"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = 'f7cdc57a6dd2'
down_revision = '3ddea9919e96'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'deleteColumn2')
    op.drop_column('projects', 'deleteColumn')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('deleteColumn', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('projects', sa.Column('deleteColumn2', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
